// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASiIq3IB4EjkYCnOjqLc0buij_TPS6xvY',
    appId: '1:663217695703:web:53d62607f5d9f091577992',
    messagingSenderId: '663217695703',
    projectId: 'easy-shopping-804ff',
    authDomain: 'easy-shopping-804ff.firebaseapp.com',
    storageBucket: 'easy-shopping-804ff.appspot.com',
    measurementId: 'G-B6RCDRYH56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY2jOktZN2K_asBY6IOBajd0UHDBzApjQ',
    appId: '1:663217695703:android:97842078a81f4c17577992',
    messagingSenderId: '663217695703',
    projectId: 'easy-shopping-804ff',
    storageBucket: 'easy-shopping-804ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR0D8RhzzeeCjw6jCNGcJEykvSv5czxhc',
    appId: '1:663217695703:ios:3f849a95a0c1f21a577992',
    messagingSenderId: '663217695703',
    projectId: 'easy-shopping-804ff',
    storageBucket: 'easy-shopping-804ff.appspot.com',
    iosBundleId: 'com.example.ecommreceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR0D8RhzzeeCjw6jCNGcJEykvSv5czxhc',
    appId: '1:663217695703:ios:3f849a95a0c1f21a577992',
    messagingSenderId: '663217695703',
    projectId: 'easy-shopping-804ff',
    storageBucket: 'easy-shopping-804ff.appspot.com',
    iosBundleId: 'com.example.ecommreceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASiIq3IB4EjkYCnOjqLc0buij_TPS6xvY',
    appId: '1:663217695703:web:318d83a1314ccec7577992',
    messagingSenderId: '663217695703',
    projectId: 'easy-shopping-804ff',
    authDomain: 'easy-shopping-804ff.firebaseapp.com',
    storageBucket: 'easy-shopping-804ff.appspot.com',
    measurementId: 'G-JP8EB4Y52M',
  );
}
